AlfiQuiz/Controllers/EncuestaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Helpers;
using System.Web.Script;
using System.Web.Script.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;



using Entidades;
using Logica;

namespace AlfiQuiz.Controllers
{
    public class EncuestaController : Controller
    {
        Encuesta_manager metodo = new Encuesta_manager();
        // GET: Encuesta
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult crearEncuesta()
        {
            return View();
        }

        [HttpPost]
        public ActionResult crearEncuesta(string json)
        {

            if (Session["usuario"] != null)
            {
                UsuarioEmpresa usu = (UsuarioEmpresa)Session["usuario"];
                JObject data = JObject.Parse(json);
                data.Add("usuario", usu.codigo_usuario_empresa);

                string respuesta = metodo.crearEncuesta(data);

                return View();
            }

            
            
            //var lista = JsonConvert.DeserializeObject<List<Encuesta>>(jarray);
            //foreach(Encuesta e in lista)
            //{
            //    int cod = e.codigo_encuesta;
            //}
            return Content("");
        }
    }
}

AlfiQuiz/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AlfiQuiz.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AlfiQuiz/Controllers/PromocionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Entidades;
using Logica;

namespace AlfiQuiz.Controllers
{
    public class PromocionController : Controller
    {
        // GET: Promocion

        Promocion_manager metodo = new Promocion_manager();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult listarPromocion()
        {
            if (Session["usuario"] != null)
            {
                UsuarioEmpresa usu = (UsuarioEmpresa)Session["usuario"];

                return View(metodo.listarPromocion(usu.codigo_usuario_empresa));
            }
            return null;            
        }

        public ActionResult crearPromocion()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View(new Promocion());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Promocion model)
        {
            var validImageTypes = new string[]
            {
                "image/gif",
                "image/jpeg",
                "image/pjpeg",
                "image/png"
            };

            if (model.ImageUpload == null || model.ImageUpload.ContentLength == 0)
            {
                ModelState.AddModelError("ImageUpload", "This field is required");
            }
                else if (!validImageTypes.Contains(model.ImageUpload.ContentType))
            {
                ModelState.AddModelError("ImageUpload", "Please choose either a GIF, JPG or PNG image.");
            }

            if (ModelState.IsValid)
            {

                if (model.ImageUpload != null && model.ImageUpload.ContentLength > 0)
                {
                    UsuarioEmpresa usu = (UsuarioEmpresa)Session["usuario"];
                    if (usu != null)
                    {
                        model.codigo_usuario_empresa = usu.codigo_usuario_empresa;
                        model.imagen = model.ImageUpload.FileName;

                        string uri = "H:\\Visual Studio\\AlfiQuiz\\ServicioRestPublishing\\App_Data\\img\\" + model.ImageUpload.FileName;
                        model.ImageUpload.SaveAs(uri);

                        if (metodo.crearPromocion(model))
                        {
                            return RedirectToAction("listarPromocion");
                        }
                    }     
                }
            }
            return RedirectToAction("Create");
        }

        [HttpPost]
        public ActionResult crearPromocion(Promocion prom)
        {
            if (ModelState.IsValid)
            {
                UsuarioEmpresa usu = (UsuarioEmpresa)Session["usuario"];
                if (usu!=null)
                {
                    prom.codigo_usuario_empresa = usu.codigo_usuario_empresa;
                    if (metodo.crearPromocion(prom))
                    {
                        return RedirectToAction("listarPromocion");
                    }
                }
            }
            return RedirectToAction("crearPromocion");
        }
        
    }
}

AlfiQuiz/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Entidades;
using Logica;

namespace AlfiQuiz.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario

        Usuario_manager metodo = new Usuario_manager();
        

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ingresar()
        {
            return View();
        }

        public ActionResult cerrarSesion()
        {
            Session["usuario"] = null;
            return RedirectToAction("ingresar");
        }

        [HttpPost]
        public ActionResult ingresar(Usuario usu)
        {
            if (ModelState.IsValid)
            {
                Usuario usuResponse = metodo.ingresar(usu);
                if(usuResponse != null)
                {
                    int tipoUsuario = usuResponse.tipo;
                    if(tipoUsuario == 1)
                    {
                        return RedirectToAction("inicioUsuarioPersona",new { id = usuResponse.codigo});
                    } else
                    {
                        return RedirectToAction("inicioUsuarioEmpresa", new { id = usuResponse.codigo });
                    }
                }
            }
            return null;
        }

        public ActionResult inicioUsuarioPersona(int id)
        {
            UsuarioPersona usu = metodo.buscarUsuarioPersona(id);

            if (usu != null)
            {
                if (Session["usuario"] == null)
                {
                    Session["usuario"] = usu;
                    return View(usu);
                }
            }

            return RedirectToAction("ingresar");

        }

        public ActionResult inicioUsuarioEmpresa(int id)
        {
            UsuarioEmpresa usu = metodo.buscarUsuarioEmpresa(id);

            if (usu != null)
            {
                if (Session["usuario"] == null)
                {
                    Session["usuario"] = usu;
                    return View(usu);
                }
            }

            return RedirectToAction("ingresar");
        }

        public ActionResult registrarUsuarioPersona()
        {
            return View();
        }

        [HttpPost]
        public ActionResult registrarUsuarioPersona(UsuarioPersona usu)
        {
            if (ModelState.IsValid)
            {
                if (metodo.registrarUsuarioPersona(usu))
                {
                    return RedirectToAction("ingresar");
                }
            }
            return RedirectToAction("ingresar");
        }

        public ActionResult registrarUsuarioEmpresa()
        {
            return View();
        }

        [HttpPost]
        public ActionResult registrarUsuarioEmpresa(UsuarioEmpresa usu)
        {
            if (ModelState.IsValid)
            {
                if (metodo.registrarUsuarioEmpresa(usu))
                {
                    return RedirectToAction("ingresar");
                }
            }
            return RedirectToAction("ingresar");
        }
    }
}

AlfiQuiz/Views/Encuesta/crearEncuesta.cshtml
@{
    ViewBag.Title = "crearEncuesta";
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function() {
        @*let json = {
            encuesta: [
                {
                    codigo_encuesta: '1',
                    codigo_usuario_empresa: '1',
                    nombre: 'prueba',
                    fecha_inicio: '01/01/01',
                    fecha_fin: '01/01/01',
                    token: '00000',
                    limite_registro: '1000',
                    bonificacion: '50',
                    estado_registro: '1'
                },
                {
                    codigo_encuesta: '1',
                    codigo_usuario_empresa: '1',
                    nombre: 'prueba',
                    fecha_inicio: '01/01/01',
                    fecha_fin: '01/01/01',
                    token: '00000',
                    limite_registro: '1000',
                    bonificacion: '50',
                    estado_registro: '1'
                }
            ]
        }

        $.ajax({
            type: 'POST',
            url: '@Url.Action("crearEncuesta","Encuesta")',
            data: {
                //json: JSON.stringify(json)
                json: JSON.stringify(json)
            },
            success: function (data) {
                console.log(data)
            }
        })*@
    })

    let numeroPregunta = 0;
    let jsonEncuesta = {};

    let crearPregunta = (tipo) => {
        //let row = $('#divPregunta').html();
        let row = '';
        row += '<div class="pregunta">';
        row += '<hr>';
        row += '<div class="form-group">';
        row += '<input type="hidden" value="'+ tipo +'">';
        row += '<label>Pregunta ' + (++numeroPregunta) + ': (' + (tipo != 0 ? 'Comentario' : 'Alternativas') +')</label>';
        row += tipo != 0 ? '' : '<button class="btn btn-warning pull-right" onclick="crearAlternativa(' + numeroPregunta + ')">Agregar alternativa</button>';
        row += '<textarea class="form-control txtPregunta"></textarea>';
        row += '</div>';
        row += tipo != 0 ? '' : '<div id="divAlternativa' + (numeroPregunta) + '" class="grupoAlternativa col-sm-offset-1"></div>';

        $('#divPregunta').append(row);
    }

    let crearAlternativa = (numero) => {
        let alternativa = $('#divAlternativa' + numero).children('.form-group').length;
        //let html = $('#divAlternativa' + numero).html();
        let html = '';
        html += '<div class="form-group">';
        html += '<label>Alternativa ' + (++alternativa) + ':</label>';
        html += '<input class="txtAlternativa form-control">';
        html += '</div>';

        $('#divAlternativa' + numero).append(html);
    }

    let obtenerData = () => {
        let preguntas = [];

        $('.pregunta').each(function (i, v) {
            let tipoPregunta = $(this).find('input[type="hidden"]').val();
            let obj = {
                tipoPregunta: tipoPregunta,
                pregunta: $(this).find('textarea').val()
            }
            if (tipoPregunta == 0) {
                let alternativas = [];
                $(this).find('.txtAlternativa').each(function (ind, val) {
                    alternativas.push($(val).val());
                })
                obj.alternativas = alternativas;
            }
            preguntas.push(obj);
        })

        let nombreEncuesta = $('#txtNombreEncuesta').val();

        jsonEncuesta = {
            nombreEncuesta: nombreEncuesta,
            preguntas: preguntas
        }
    }

    let vistaPrevia = () => {

        obtenerData();

        let html = '';
        html += '<div class="row">';
        html += '<div class="col-md-10 col-md-offset-1">';
        html += 'Nombre de encuesta: ' + jsonEncuesta.nombreEncuesta;
        html += '<div class="col-md-offset-1">';
        jsonEncuesta.preguntas.forEach(function (valor, indice) {
            html += '<hr>'
            html += 'Pregunta ' + (indice + 1) + ':<br>';
            html += valor.pregunta;
            html += '<div class="col-md-offset-1">';

            if (valor.tipoPregunta == 0) {
                html += '<form>'
                valor.alternativas.forEach(function (val, ind) {
                    html += '<div class="radio">';
                    html += '<label><input type="radio" name="opcion">' + val + '</label>';
                    html += '</div>';
                })
                html += '</form>'
            } else {
                html += '<div class="form-group">';
                html += 'Comentario:';
                html += '<textarea class="form-control"></textarea>';
                html += '</div>';
            }
            html += '</div>';
        })
        html += '</div>';
        html += '</div>';
        html += '</div>';

        $('#modal_vista_previa .modal-body').html(html);
        $('#modal_vista_previa').modal('show');
    }

    let crearEncuesta = () => {

        obtenerData();

        let fechaInicio = $('#dtFechaInicio').val();
        let fechaFin = $('#dtFechaFin').val();
        let bonificacion = $('#txtBonificacion').val();
        let limite = $('#txtLimite').val();
        let token = $('input[name="token"]:checked').val();

        jsonEncuesta.fechaInicio = fechaInicio;
        jsonEncuesta.fechaFin = fechaFin;
        jsonEncuesta.bonificacion = bonificacion;
        jsonEncuesta.limite = limite;
        jsonEncuesta.token = token;

        console.log(jsonEncuesta);


        $.ajax({
            type: 'POST',
            url: '@Url.Action("crearEncuesta","Encuesta")',
            data: {
                //json: JSON.stringify(json)
                json: JSON.stringify(jsonEncuesta)
            },
            success: function (data) {
                console.log(data)
            }
        })
    }
</script>

<h2>Creacion de encuesta</h2>
<br>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="row">
            <button class="btn btn-info pull-right" data-toggle="modal" data-target="#modal_crear_encuesta">Crear encuesta</button>
            <button class="btn btn-primary pull-right" onclick="vistaPrevia()">Vista previa</button>
            <div class="form-group">
                <label>Nombre de encuesta:</label>
                <input class="form-control" id="txtNombreEncuesta" />
            </div>
        </div>
        <div id="divPregunta">
            @*<div class="form-group">
                    <div class="row">
                        <div class="form-group">
                            <label>Pregunta 1</label><button class="btn btn-success pull-right">Agregar alternativa</button>
                            <input class="form-control txtPregunta"/>
                        </div>
                        <div class="row" id="divAlternativa1">

                        </div>
                    </div>
                </div>*@
        </div>
        <hr>
        <button class="btn btn-success pull-right" data-toggle="modal" data-target="#modal_tipo_pregunta">Agregar pregunta</button>
    </div>
</div>

@*Modales*@
@*Modal tipo de pregunta*@

<div class="modal fade" id="modal_tipo_pregunta" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Elija el tipo de pregunta</h4>
            </div>
            <div class="modal-body">
                <button class="btn btn-success" onclick="crearPregunta(0)" data-dismiss="modal">Alternativa</button>
                <button class="btn btn-primary" onclick="crearPregunta(1)" data-dismiss="modal">Comentario</button>
                <button class="btn btn-danger" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

@*Modal vista previa*@
<div class="modal fade" id="modal_vista_previa" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Vista previa</h4>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button class="btn btn-danger" data-dismiss="modal">Aceptar</button>
            </div>
        </div>
    </div>
</div>

@*Modal confirmacion para la creacion*@
<div class="modal fade" id="modal_crear_encuesta" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Configuraciones</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label>Fecha de inicio:</label>
                        <input type="date" id="dtFechaInicio" class="form-control"/>
                    </div>
                    <div class="col-md-6 form-group">
                        <label>Fecha de fin:</label>
                        <input type="date" id="dtFechaFin" class="form-control"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 form-group">
                        <label>Bonificacion:</label>
                        <input type="number" id="txtBonificacion"  class="form-control"/>
                    </div>
                    <div class="col-md-4 form-group">
                        <label>Limite de encuestas:</label>
                        <input type="number" id="txtLimite"  class="form-control"/>
                    </div>
                    <div class="col-md-4 form-group">
                        <label>Encuesta:</label>
                        <div class="radio">
                            <label><input type="radio" name="token" value="1"/>Publico</label>
                        </div>
                        <div class="radio">
                            <label><input type="radio" name="token" value="0"/>Privado</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" onclick="crearEncuesta()">Aceptar</button>
                <button class="btn btn-danger" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

AlfiQuiz/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AlfiQuiz/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AlfiQuiz/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

AlfiQuiz/Views/Promocion/Create.cshtml
@model Entidades.Promocion

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<form action="" method="post" enctype="multipart/form-data">
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Promocion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imagen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imagen, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.bonificacion_pago, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.bonificacion_pago, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.bonificacion_pago, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha_inicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha_inicio, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.fecha_inicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha_fin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha_fin, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.fecha_fin, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Caption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Caption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Caption, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUpload, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ImageUpload, new { @type = "file", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registrar promocion" class="btn btn-success" />
            </div>
        </div>
    </div>
</form>


    <div>
        @Html.ActionLink("Volver a la lista", "listarPromocion")
    </div>

AlfiQuiz/Views/Promocion/crearPromocion.cshtml
@model Entidades.Promocion

@{
    ViewBag.Title = "crearPromocion";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Promocion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.codigo_promocion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.codigo_promocion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.codigo_promocion, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.codigo_usuario_empresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.codigo_usuario_empresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.codigo_usuario_empresa, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.descripcion, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.imagen, new { type = "file", @class = "control-label col-md-2" } )
                @Html.ValidationMessageFor(model => model.imagen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.bonificacion_pago, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.bonificacion_pago, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.bonificacion_pago, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha_inicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.fecha_inicio, new { type = "date" ,@class= "control-label col-md-2" })
                @Html.ValidationMessageFor(model => model.fecha_inicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha_fin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.fecha_fin, new { type = "date", @class = "control-label col-md-2" } )
                @Html.ValidationMessageFor(model => model.fecha_fin, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.estado_registro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.estado_registro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.estado_registro, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear promocion" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listar promocion", "listarPromocion")
</div>

AlfiQuiz/Views/Usuario/inicioUsuarioEmpresa.cshtml
@model Entidades.UsuarioEmpresa

@{
    ViewBag.Title = "inicioUsuarioEmpresa";
}

<h2>Bienvenido @Html.DisplayFor(model => model.nombre)</h2>

<div class="form-horizontal">
    <div class="form-group">
        @Html.ActionLink("Mis promociones","listarPromocion","Promocion",null, new { @class = "btn btn-success" })
    </div>
    <div class="form-group">
        @Html.ActionLink("Mis encuestas", "crearEncuesta", "Encuesta",null, new { @class = "btn btn-warning" })
    </div>
    @*<div class="form-group">
        @Html.LabelFor(model => model.codigo_usuario_empresa, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.DisplayNameFor(model => model.codigo_usuario_empresa)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.DisplayTextFor(model => model.nombre)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ruc, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.DisplayTextFor(model => model.ruc)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.correo, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.DisplayTextFor(model => model.correo)
    </div>*@
</div>